version: 0.0.0.{build}
image: WMF 5

install:
    - git clone https://github.com/PowerShell/DscResource.Tests

    - npm --silent install

    - ps: |
        $moduleName = 'PFE-SharePoint'
        $mainModuleFolder = "PowerShell\Modules\$moduleName"
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask
        
build: off

